name = "TNRKit"
uuid = "7dfc3ef0-df9b-475f-b8e2-b91f34f5d84d"
authors = ["Victor Vanthilt, Adwait Naravane, Atsushi Ueda and contributors"]
version = "0.3.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
OptimKit = "77e91f04-9b3b-57a6-a776-40b61faaebe0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Combinatorics = "1.1.0"
DocStringExtensions = "0.9.4"
FastGaussQuadrature = "1.1.0"
KrylovKit = "0.10"
LoggingExtras = "~1.0"
OptimKit = "0.4.0"
QuadGK = "2.11.2"
SpecialFunctions = "2.6.1"
TensorKit = "0.14"
Zygote = "0.7.7"
julia = "1.11"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QuadGK"]
